### ISSUE TITLE
Run Service Worker Gateway tests on CI (was: Service Worker Gateway is borked)

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/old-js-ipfs-website#199] opened 2018-11-16 08:14 UTC
I tried with Firefox and Chrome and both fail.

![image](https://user-images.githubusercontent.com/1211152/48606478-97164800-e977-11e8-9c8b-aaebdccccc2e.png)

![image](https://user-images.githubusercontent.com/1211152/48606486-9a113880-e977-11e8-96e2-b5f4cf3796e3.png)

This needs to get automatically tested.

**Comment by daviddias** [comment] 2018-11-16 20:12
What's the update here?

**Comment by daviddias** [comment] 2018-11-17 08:01
Seems that the Service Worker is correctly getting installed on dev.ipfs.io, however, loading some of the example websites takes infinity, example:

- https://dev.js.ipfs.io/ipfs/QmX7uKymLyHHdsVY9yXbj54AdKSaLuamXJHcXyWfKQ6fus
- https://dev.js.ipfs.io/ipfs/QmfQiRPTxVTT31ecDMAcUgTSTDt2HdPHKTuDWnD7T689oi

**Comment by PedroMiguelSS** [comment] 2018-11-17 11:30
Looking into it @daviddias

**Comment by PedroMiguelSS** [comment] 2018-11-17 12:09
You can now use the service worker properly on [js.ipfs.io](https://js.ipfs.io/) as we shipped the new version. We are now looking into the time it takes to load the example websites.

//cc: @vasco-santos @daviddias

**Comment by vasco-santos** [comment] 2018-11-17 12:16
Regarding the reported speed issue, the first hash for `Awesome IPFS` is working properly for us. The second one, `peer-pad` takes infinity for us, as well. After an analysis, we are having a connectivity issue, as you can see in the following screenshot. From my local daemon, I can get the `Awesome IPFS`, but not `peer-pad`. Or we are lacking any bootstrap node that `go-ipfs` has, since using the public gateway in `ipfs.io` we can reach `peer-pad`, or `peer-pad` was not properly added to the `preloader` gateways, or we have an issue with `js-ipfs`.

![image](https://user-images.githubusercontent.com/7295071/48660932-f3559680-ea61-11e8-9098-1b7b36123198.png)

@alanshaw @daviddias any idea? Meanwhile we should create a new issue for this, as it does not seem a problem with `js.ipfs.io` nor `service-worker-gateway`. @daviddias please just confirm that we are having the expected behavior for the service worker now in production.

**Comment by vasco-santos** [comment] 2018-11-17 12:32
Ok, so the problem is that the `peer-pad` hash is not correct 🤔 

it shoud be:

```sh
➜  js-ipfs git:(feat/ipns-over-dht) ✗ dig +short txt _dnslink.peerpad.net
"dnslink=/ipfs/QmXRTzu4dUFnA1nLR7ogifE1EeY2hEsVyQNkZu4CzF6g2v"
```

We will update it

**Comment by daviddias** [comment] 2018-11-17 13:04
@vasco-santos it isn't the case that the PeerPad hash was incorrect, it means it got lost (unpinned) //cc @pgte @jimpick. Updating it will solve it for now, but we need to make sure we don't loose pins.

**Comment by vasco-santos** [comment] 2018-11-17 13:08
true! I meant that the hash there is not the most recent for `peer-pad`, but we still had an issue with it.

**Comment by PedroMiguelSS** [comment] 2018-11-17 17:59
Hashes are updated now on [js.ipfs.io](https://js.ipfs.io/). It solves our problem for now but we will manage to a definitive solution soon.

**Comment by PedroMiguelSS** [comment] 2018-11-22 16:49
Service worker tests are now running on the `pre-push` hook. This is a temporary solution until we get [ipfs/infrastructure#455](https://github.com/ipfs/infrastructure/issues/455) solved.

**Comment by PedroMiguelSS** [comment] 2018-12-18 09:45
Preventive measures were taken: the tests are running on the `pre-push` hook. This is not the final solution as it makes a lot more sense having them running on the CI. I'll update the priority label to `P3 - Low` and I'll close this issue as soon as [ipfs/infrastructure#455](https://github.com/ipfs/infra/issues/455) gets solved.

**Closed** 2023-10-30 21:46 UTC
Labels: P3, status/blocked
